version: '3'

services:
  db:
    image: mysql:latest
    container_name: wp2db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wp2dbmysql
    volumes: 
      - wp2dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.5.3-fpm-alpine
    container_name: wp2
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wp2dbmysql
    volumes:
      - wp2files:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.5-alpine
    container_name: wp2webserver
    restart: unless-stopped
    ports:
      - "8092:80"
    volumes:
      - wp2files:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  wp2files:
  wp2dbdata:

networks:
  app-network:
    driver: bridge  